openapi: 3.0.3
info:
  title: Inditex Prices API
  description: "REST API to query applicable product prices based on brand, product, and date"
  version: "1.0"
servers:
- url: http://localhost:8080
paths:
  /price:
    get:
      tags:
      - Price
      operationId: getPrice
      parameters:
      - name: date
        description: "Date to which the applicable price belongs"
        in: query
        required: true
        schema:
          type: string
          format: date-time
          example: "2020-06-14-00.00.00"
      - name: productId
        description: "Product id to which the applicable price belongs"
        in: query
        required: true
        schema:
          type: integer
          format: int64
          example: 35455
          minimum: 0
      - name: brandId
        description: "Brand id to which the applicable price belongs"
        in: query
        required: true
        schema:
          type: integer
          format: int32
          example: 1
          minimum: 0
      responses:
        "200":
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/PriceResponse'
components:
  schemas:
    PriceResponse:
      type: object
      properties:
        productId:
          type: integer
          format: int64
          example: 35455
        brandId:
          type: integer
          format: int32
          example: 1
        priceList:
          type: integer
          format: int32
          example: 1
        startDate:
          type: string
          format: date-time
          example: "2020-06-14-00.00.00"
        endDate:
          type: string
          format: date-time
          example: "2020-12-31-23.59.59"
        price:
          type: number
          format: float
          example: 35.50
        currency:
          type: string
          example: EUR